### ISSUE TITLE
Simulation output delay one cycle

### ISSUE THREAD

**Issue by YanjenChen** [ric2k1/gv0-socv#1]
Seems like the output of the property logic `p` will delay one cycle in HW1.
I've used the following patterns for the input:
```
1 0 0 0 0
3 0 0 3 0
2 2 2 2 2
```

Which will produce the following output:
```
==========================================
= cycle 10
==========================================
serviceTypeOut= 0
itemTypeOut= 0
coinOutNTD_1= 0
coinOutNTD_5= 0
coinOutNTD_10= 0
coinOutNTD_50= 0
p= 0

==========================================
= cycle 11
==========================================
serviceTypeOut= 1
itemTypeOut= 0
coinOutNTD_1= 0
coinOutNTD_5= 0
coinOutNTD_10= 0
coinOutNTD_50= 0
p= 1
```

Since the logic of `p` will only produce `1` when `serviceTypeOut` is `0`, the `p= 1` in cycle 11 should actually output at cycle 10.

**Comment by HHHUUUGGGOOO** [comment]
Hi, 

Thanks for your question~ I think the command has no problem, you can check "gv0-socv/.sim_main.cpp" to trace how the output message generated! 

As for your issue, it is just your misunderstanding on vending machine design (vending.v), you can trace the RTL code again, the "cycle 10" result is not only triggered when "serviceType == `SERVICE_OFF"! The bug is indeed happening at cycle 11~ 

Sorry that I could not delve into more, since the detailed is what the HW1 needs you to finish, good luck for your homework~

Best Regards

**Comment by YanjenChen** [comment]
Hi Hugo,

But according to the RTL design, `p` is defined as follows.
```v
assign p = initialized && (serviceTypeOut == `SERVICE_OFF) && (itemTypeOut == `ITEM_NONE) && (outExchange != inputValue); // catch the bug
```
This means that at cycle 11, `serviceTypeOut= 1` (a.k.a. `define SERVICE_ON      2'b01`), then `p` has no chance to be logical 1.

If there is any misunderstanding, please let me know, thank you~

**Comment by HHHUUUGGGOOO** [comment]
Hi, 

Finally we found that maybe it is because we use "cxxrtl" under yosys as our simulator. 

As fig.1 shown, the 1-cycle-delay is because "p" is triggered in negative edge, hence display in the next (posedge clk) cycle. But it is quite wierd... 

So we try reset output wire "p" initially, and found that the "p" is triggered at cycle 10 as expected. However, output wire theoretically no need to be reset, so our conclusion is that the open source simlator is not complete as industrial tool does (ncverilog, etc.) 

Thanks for your observation, but it will not affect the homework1, so no worry!

Best Regards

<img width="838" alt="Screen Shot 2023-03-09 at 5 26 22 PM" src="https://user-images.githubusercontent.com/45988775/223978521-63004e3c-f1f2-4eb7-86fe-3af140a345d8.png">

<img width="752" alt="Screen Shot 2023-03-09 at 5 25 10 PM" src="https://user-images.githubusercontent.com/45988775/223978220-9f9f4713-81d1-49a4-9fb2-571020220a5e.png">

<img width="838" alt="Screen Shot 2023-03-09 at 5 25 28 PM" src="https://user-images.githubusercontent.com/45988775/223978298-0f1d32b8-cf51-4c13-8149-ce19fbbe98f9.png">

**Comment by YanjenChen** [comment]
Hi Hugo,

Thanks for your work! After adding `p <= 0` (I know it is weird, but seems like we need to do so in order to get the correct result in this homework), I can get the correct simulation result.
